version: "3.8"

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - docker
    environment:
      - DOCKER_HOST=tcp://docker:2375
      - DOCKER_TLS_CERTDIR=""

  docker:
    image: docker:dind
    container_name: docker_in_docker
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=""
    ports:
      - "2375:2375"
